name: tua2_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  url_launcher: ^6.3.1
  geocoding: ^5.0.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome_tua2.png
    - assets/images/logo.png