// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(flutter run
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5BuSZWEHhZpwkQDmL7wX7WDYWCDfn5xk',
    appId: '1:952171685021:web:9123e0ba933aaab7c7e074',
    messagingSenderId: '952171685021',
    projectId: 'tua2-5045c',
    authDomain: 'tua2-5045c.firebaseapp.com',
    storageBucket: 'tua2-5045c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKb0mE9sr3s_Zac7wj_mKcYjSRdQVcYmg',
    appId: '1:952171685021:android:e422f8f72cb2b9ebc7e074',
    messagingSenderId: '952171685021',
    projectId: 'tua2-5045c',
    storageBucket: 'tua2-5045c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZxI61nNYi-WB_gXeI0obZtgRtGTV4Syg',
    appId: '1:952171685021:ios:ba8a2514094d6054c7e074',
    messagingSenderId: '952171685021',
    projectId: 'tua2-5045c',
    storageBucket: 'tua2-5045c.firebasestorage.app',
    iosBundleId: 'com.example.tua2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZxI61nNYi-WB_gXeI0obZtgRtGTV4Syg',
    appId: '1:952171685021:ios:ba8a2514094d6054c7e074',
    messagingSenderId: '952171685021',
    projectId: 'tua2-5045c',
    storageBucket: 'tua2-5045c.firebasestorage.app',
    iosBundleId: 'com.example.tua2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5BuSZWEHhZpwkQDmL7wX7WDYWCDfn5xk',
    appId: '1:952171685021:web:bd47d28274e479cfc7e074',
    messagingSenderId: '952171685021',
    projectId: 'tua2-5045c',
    authDomain: 'tua2-5045c.firebaseapp.com',
    storageBucket: 'tua2-5045c.firebasestorage.app',
  );
}
